### ISSUE TITLE
CI/CD の標準化

### ISSUE THREAD

**Issue by daiki-akimoto-jdsc** [jdsc-eng/development-standard#19]
## Backgrouds
- CI/CD はある程度使われているが、 PJ によてフローがバラバラだったりする
- またテンプレートコードが提供されておらず、構築に時間がかかる

## Tasks
- [ ] (Optional) CI/CD ツールの選定
- [ ] CI/CD の典型的なフローについてドキュメント化(CI/CD が不明な人も多いので)
- [ ] CI/CD のコードのテンプレート化

## Outputs
- (Confluence)
- (GitHub)
- (Optional; 技術比較のスライド)

## Memo
- Cloud Build ともう一つぐらい CI/CD ツール検証してみても良いと思ってる
